# Generated by Django 5.2.6 on 2026-04-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FalooBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=20, unique=True, verbose_name='书籍ID')),
                ('title', models.CharField(max_length=255, verbose_name='书名')),
                ('author', models.CharField(max_length=100, verbose_name='作者')),
                ('cover_url', models.CharField(max_length=500, verbose_name='封面链接')),
                ('main_category', models.CharField(max_length=50, verbose_name='主分类')),
                ('sub_category', models.CharField(max_length=50, verbose_name='子分类')),
                ('read_count', models.BigIntegerField(default=0, verbose_name='阅读量')),
                ('word_count', models.BigIntegerField(default=0, verbose_name='字数')),
                ('update_time', models.CharField(max_length=50, verbose_name='更新时间')),
                ('tags', models.CharField(max_length=500, verbose_name='标签')),
                ('introduction', models.TextField(verbose_name='简介')),
            ],
            options={
                'db_table': 'faloo_books',
                'managed': False,
            },
        ),
    ]
