# Generated by Django 5.2.6 on 2026-04-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_admin_alter_faloobook_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='邮箱')),
                ('avatar', models.CharField(default='https://via.placeholder.com/40?text=User', max_length=255, verbose_name='头像')),
                ('bookshelf', models.TextField(default='[]', verbose_name='书架')),
                ('click_history', models.TextField(default='[]', verbose_name='点击历史')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'users',
            },
        ),
    ]
