# Generated by Django 5.2.6 on 2026-04-19 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book_id', models.CharField(max_length=20, verbose_name='书籍ID')),
                ('score', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='评分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '书籍评分',
                'verbose_name_plural': '书籍评分',
                'db_table': 'ratings',
                'unique_together': {('user', 'book_id')},
            },
        ),
    ]
