# Generated by Django 5.2.6 on 2026-04-19 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBookshelf',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='书架ID')),
                ('book_id', models.CharField(max_length=20, verbose_name='书籍ID')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序序号')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户书架',
                'verbose_name_plural': '用户书架',
                'db_table': 'user_bookshelf',
                'unique_together': {('user', 'book_id')},
            },
        ),
    ]
