# Generated by Django 5.2.6 on 2026-04-25 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_faloobook_options_alter_rating_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActionLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='行为ID')),
                ('book_id', models.CharField(max_length=20, verbose_name='书籍ID')),
                ('action_type', models.CharField(choices=[('like', '收藏'), ('dislike', '不感兴趣')], max_length=10, verbose_name='行为类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户行为日志',
                'verbose_name_plural': '用户行为日志',
                'db_table': 'user_action_logs',
            },
        ),
    ]
